language: generic

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.28.5/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - yarn install

jobs:
  include:
    - stage: build
      script: docker-compose up --build -d
    
    - stage: test
      script:
      - docker-compose run backend python3 manage.py test

after_script:
  - docker-compose down --remove-orphans

notifications:
  email: false