language: python

python:
  - 3.6

sudo: required

services:
  - docker

before_install:
  - pip3 install docker-compose

jobs:
  include:
    - stage: build
    - script: docker-compose up --build -d

after_script:
  - docker-compose down --remove-orphans

notifications:
  email: false