language: python

python:
  - 3.6

sudo: required

branches:
    only:
        - master

services:
  - docker

before_install:
  - pip3 install docker-compose


matrix:
    include:
        - env: TARGET=api/api
        - env: TARGET=client

script:
  - docker-compose up --build -d
  # - if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET;

after_script:
  - docker-compose down --remove-orphans

notifications:
  email: false