language: python

python:
  - 3.6

sudo: required

branches:
    only:
        - master

services:
  - docker

before_install:
  - pip3 install docker-compose

script:
  - docker-compose up --build -d

after_script:
  - docker-compose down --remove-orphans

notifications:
  email: false