language: generic

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.28.5/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - yarn install
  - npm install

install:
  - pip install coveralls

jobs:
  include:
    - stage: build
      script: docker-compose up --build -d
    - stage: test
      script:
      - docker-compose run backend python3 manage.py test
      # - docker-compose run frontend quasar test --unit jest
      - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

after_script:
  - docker-compose down --remove-orphans

after_success:
  - coveralls

notifications:
  email: false