language: python

python:
  - 3.6

services:
  - docker

before_install:
  - pip3 install docker-compose
  - yarn install

jobs:
  include:
    - stage: build
      script: docker-compose up --build -d
    
    - stage: test
      script:
      - yarn quasar test --unit jest
      - docker-compose run api ./test_api.sh

after_script:
  - docker-compose down --remove-orphans

notifications:
  email: false