language: python

python:
  - 3.6

services:
  - docker

sudo: required

before_install:
  - pip3 install docker-compose

script:
  - docker-compose up --build -d
  # - npm ci
  # - npm run test:coveralls

# jobs:
#   include:
#     - stage: build
#     - stage: test
#       script:
#       - docker-compose run client yarn quasar test --unit jest
#       - docker-compose run api ./test_api.sh

after_script:
  - docker-compose down --remove-orphans

notifications:
  email: false