language: generic

python:
  - 3.6

services:
  - docker

before_install:
  - pip3 install docker-compose
  - yarn install

jobs:
  include:
    - stage: build
      script: docker-compose up --build -d
    
    - stage: test
      script:
      - docker-compose run backend python3 manage.py test

after_script:
  - docker-compose down --remove-orphans

notifications:
  email: false